### PR TITLE
Add ALINX AX7010 board support

### PR DESCRIPTION
**Pull request by ggangliu**
Add a new board zynq xc7z010 support. And I have tested BIOS which is working well.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Hi @ggangliu,

thanks for the board support. Do you have more information about this board?

**Comment by ggangliu** [comment]
> 

What info should I provide? Is there any example I can ref?

**Comment by enjoy-digital** [comment]
From PR I'm not able to know which board it is. Do you have a link to a description of the board? or where it is available?

**Comment by tcal-x** [comment]
@ggangliu , these files are named for the device (Xilinx Zynq xc7z010) -- usually the file names include the distinctive _board_ name like "Fomu" or "Arty A7".   Does your board have a  unique name?   Is it for sale online somewhere?

**Comment by ggangliu** [comment]
Thanks @tcal-x  and @enjoy-digital ,
I've got your point. I guess the name should be Alinx AX7010. Below is a online link. Please help take a look and please help confirm what name I should use, thanks very much.

https://www.xilinx.com/products/boards-and-kits/1-1bkpiul.html

**Comment by enjoy-digital** [comment]
Thanks @ggangliu, I would just need 2 changes to be able to merge:
- Can you replace the copyrights with yours?
- Can you rename the platform/target to `alinx_ax7010.py`

**Comment by ggangliu** [comment]
> 



> Thanks @ggangliu, I would just need 2 changes to be able to merge:
> 
>     * Can you replace the copyrights with yours?
> 
>     * Can you rename the platform/target to `alinx_ax7010.py`

Yea, of course, really thanks @enjoy-digital

**Comment by enjoy-digital** [comment]
Thanks @ggangliu! This looks good now and has been merged. Thanks a lot for this first contribution, one more board supported :)

**Comment by enjoy-digital** [comment]
@ggangliu: I just did some minor changes on top of your PR with https://github.com/litex-hub/litex-boards/commit/9faa805ab92c901dd1b6f6adfec5b440ccc4d56e.

**Comment by ggangliu** [comment]
> @ggangliu: I just did some minor changes on top of your PR with [9faa805](https://github.com/litex-hub/litex-boards/commit/9faa805ab92c901dd1b6f6adfec5b440ccc4d56e).

Really thanks.

**Pull request merged**
