### PR TITLE
Preliminary support for Digilent Zybo

### PR DESCRIPTION
**Pull request by JoyBed**
I noticed there is only support for Digilent Zybo Z7 and not the older Zybo. Created support for Zybo from Z7-10 as they are similiar.

### CODE REVIEW

**Comment by JoyBed** [comment]
> ,

I closed it just recently to fix some things I missed and fixed yesterday but did not want to do much commits. I even tested it but did not had time to fully test it. I can reopen this and add changes if it would make sense.

**Comment by JoyBed** [comment]
> Sorry for delay (and I see this PR is now closed). Support for original zybo was lost with commit [b030630](https://github.com/litex-hub/litex-boards/commit/b03063023730b5ea5d649c729005d8a32175e07c) I make sense to re-add support for this version. a diff between classes shows a really few amount of differences, but adding twice I increase maintenance. In my mind It's maybe better to update existing classes to add this variant and maybe for `_io` and `_connectors` to add something like is done for `ps7_config`.

Now after thinking about it, I can just rewrite the two files for Zybo Z7 so when you specify the original zybo and not the Z7 tose zybo z7 files will be used but without the changes the commit [b030630](https://github.com/litex-hub/litex-boards/commit/b03063023730b5ea5d649c729005d8a32175e07c) brought in? Is it something you had in mind? It would have the original zybo as a variant: Zybo_Z7-10, Zybo_Z7-20, Zybo_original.

**Comment by trabucayre** [comment]
> I tested just now the newest version of files for Zybo Z7 with my modification for original Zybo support. It works! 

Great!
>So I will rewrite the target and platform files for Z7 to include a original Zybo variant based on the modifications. Then I will reopen this pull request with them.

Ok

> Can you please keep an eye on this so it can go thru faster?

Yes of course!

Just a remark: could you rebase/force-push to avoid to many commits?

**Comment by JoyBed** [comment]
> > I tested just now the newest version of files for Zybo Z7 with my modification for original Zybo support. It works!
> 
> Great!
> 
> > So I will rewrite the target and platform files for Z7 to include a original Zybo variant based on the modifications. Then I will reopen this pull request with them.
> 
> Ok
> 
> > Can you please keep an eye on this so it can go thru faster?
> 
> Yes of course!
> 
> Just a remark: could you rebase/force-push to avoid too many commits?

Seems to be done. Reopening pull request and rebasing it.

**Comment by JoyBed** [comment]
Seems like when I deleted the forked repo and then forked again for rewriting the z7 files I cant rebase/force-push. I think I will close this one and just start a new one.

**Pull request closed without merging**
