### PR TITLE
Add QMTech XC7K325T

### PR DESCRIPTION
**Pull request by hansfbaier**
I actually have forgot to contribute this one.
It actually think this has been originally written by @kazkojima , which he has shared with me.
I modified this a bit.
Have not tested in its current form,
but the LiteX build runs fine.

### CODE REVIEW

**Comment by hansfbaier** [comment]
Weird. CI fails, because --no-compile does not seem to work

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier, I'll fix CI.

**Comment by enjoy-digital** [comment]
This should be good with https://github.com/litex-hub/litex-boards/commit/e59d75f5936d7f8732e2c227d86a23285630d724.

**Comment by hansfbaier** [comment]
Thanks!

**Pull request merged**
