### PR TITLE
QMTech boards: make Artix7 bitstream/platform commands conditional on toolchain

### PR DESCRIPTION
**Pull request by hansfbaier**
I also removed setting .f4pga_device since it is identical to platform.device

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier. In the past, I tried to avoid specializing platforms/target to the requirements of the different toolchain. We agree to allow it on the Digilent Arty to still allow fast experimentation/developments but with the aim in the long term to remove it. I think the different toolchain will try to align with Vivado commands in the long terms,  so it would probably be better to handle there unsupported commands directly in the LiteX build backend for the toolchain. Ex have the build backend catch a `"set_property INTERNAL_VREF"` command and generate a Warning since not supported but also not inserting it in the generated files. This way, as the toolchain support improve, you'll just be able to modify the build backend and progressively remove the modifications, without requiring modifying the different platforms.

**Comment by hansfbaier** [comment]
Yes that totally makes sense. Can you point me to the code location where that would be?

**Comment by hansfbaier** [comment]
OK, implemented the requested changes here.

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier.

**Pull request merged**
