### PR TITLE
Add support for 5A-75E V6.0 board

### PR DESCRIPTION
**Pull request by DerFetzer**
...though it is not working with Ethernet for me, yet.

When I try current consumption goes way down and nothing happens. Except for I can probe a weird 2.5MHz clock at the SDRAM.
Does anybody have an idea?

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks, for Ethernet, you could maybe do a test by commenting out the` rst_n` definition in the Platform file and use the 25MHz from Ethernet for the SoC.

**Comment by DerFetzer** [comment]
Yes, you are right. Problem is that the 25MHz clock is generated by one of the Ethernet PHYs so it stops on PHY reset.
I added the possibility to use the ECP5 OSCG primitive for system clock.

**Comment by DerFetzer** [comment]
This is working as well. I tried that yesterday or so.
Question is what would be the preferred thing to do?
I tried removing the `rst_n` pin programmatically so you could provide a command line switch. But it did not work due to some python magic in the framework.

**Comment by enjoy-digital** [comment]
@DerFetzer ah ok, so Ethernet is working when the internal oscillator is used? Sorry i thought it was not the case. If so, we could merge and i will try to find a better solution in the next days.

**Comment by DerFetzer** [comment]
Yes, Ethernet is working. 
I did not do a full test, yet. But when I use `netboot` command from `LiteX BIOS` I can see `ARP` packets coming from the board.

**Comment by DerFetzer** [comment]
I seems like only transmitting over Ethernet is possible. Though my PC answers to the `ARP` requests there are no other packets coming from the board. This is the same with the `rst_n` pin commented out and with external clock.

The only obvious problem I see might be the same as in https://github.com/enjoy-digital/liteeth/issues/47. 
But the timing for my board is even worse:
```
Warning: Max frequency for clock '$glbnet$eth_clocks_rx$TRELLIS_IO_IN': 87.94 MHz (FAIL at 125.00 MHz)
```
In the issue you wrote that this might not be a problem but I don't know if this statement still stands with such a big timing violation.

**Comment by DerFetzer** [comment]
When I limit the Ethernet link to 100MBit/s or use a 100MBit/s switch there are not even ARP frames coming through. This is strange.

**Comment by DerFetzer** [comment]
GBit-Ethernet is working now! There is a pin swap at the RXD pins for PHY0 in the [documenation](https://github.com/q3k/chubby75/blob/master/5a-75e/hardware_V6.0.md). I will make a pull request there.

The problem with 100MBit/s persists though.

**Comment by enjoy-digital** [comment]
Thanks for the update, i think we can merge now. The ECP5RGMII Ethernet PHY hasn't been test/validated at 100Mbps so that's probably not related to the board.

**Pull request merged**
