### PR TITLE
Add board support for Terasic/Arrow SocKit, Add connectors to de0-nano

### PR DESCRIPTION
**Pull request by hansfbaier**
Hi Florent,
today I got a first running version that blinks the LEDs on the board.
There are still quite a number of things missing (DDR3 not possible because literam does not support altera yet
and no hard CPU core support),
but it is already in a useable state, and worthy to share.
The different commits are probably of not much interest to the history, so you might want to squash
all detailed commits.
Does github have a checkbox for squashing commits on merge, or do you want me to squash?

Best regards,
Hans

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier, this wil be useful yes even if not all the present peripherals of the boards are yet supported by LiteX. I'll review it and merge it very soon.

**Comment by hansfbaier** [comment]
Hi Florent, 
I added the connector descriptions to de0-nano board.

**Comment by hansfbaier** [comment]
Hi Florent, are there still issues with the commits, that prevent them from being merged?

**Comment by hansfbaier** [comment]
Hi, I squashed all the sockit-related commits, so it will be easier to review.

**Review by enjoy-digital — APPROVED** [review]
Thanks, looks good. I'm going to merge and will do some minor change to harmonize things with others boards.

**Comment by enjoy-digital** [comment]
This as been merged and minor changes have been done with:
- https://github.com/litex-hub/litex-boards/commit/4adc1b14c494ac21ac1a08c2713a631ce54bc1d1
- https://github.com/litex-hub/litex-boards/commit/537f494cbbb4c21895b5e95e09387f4fe304276c

**Comment by hansfbaier** [comment]
Thank you!

**Comment by somhi** [comment]
I have SoCKit board as well, and I'm part of a larger community who bought this board recently.
Yesterday I built and loaded the arrow target and saw the leds blinking. That's cool.  
After that I spent a few hours trying to get a terminal output from the Crossover serial port with the wishbone-tool without any success. Now that I found this merge I'm afraid there is no such terminal output yet as you said it's "a first running version that blinks the LEDs on the board."
Hans Baier, can you please clarify if there is terminal output, and the how to get it ?
Second question, Linux on Litex for SoCKit target is still a long way to go?

Not sure if it's the proper way to contact you, as I haven't found the issue tab on your personal github Hans.

**Comment by hansfbaier** [comment]
Hi,
I also head difficulties getting Crossover with terminal running on other
boards (Acorn CLE-*, Colorlight 5A-75B).
I didn't try it on the SocKit yet, but as far as I have experienced on the
other boards,
they could be related to timing closure problems.
My commit provides all the pin mappings and connectors, which will provide
the basis for building a full SoC later.
But this cannot happen, until LiteDRAM supports DDR3 memory on Altera
FPGAs, which is not the case yet.
Only when LiteDRAM is implemented for those, we would have all the
components ready to build a whole SoC on the sockit.

Best regards,
Hans

Am So., 31. Jan. 2021 um 18:10 Uhr schrieb somhi <notifications@github.com>:

**Comment by hansfbaier** [comment]
Hi @somhi ,
I just found a solution to get an uart.
Use this file to build the system:
```python
#!/usr/bin/env python3

from migen                import Instance
from migen.fhdl.structure import Signal, ClockSignal, ResetSignal

from litex_boards.platforms            import arrow_sockit
from litex_boards.targets.arrow_sockit import BaseSoC
from litex.soc.cores                   import uart
from litex.soc.integration.builder     import Builder
from litex.build.generic_platform      import Subsignal, Pins, IOStandard
from litescope.core                    import LiteScopeAnalyzer



class SockitPlayground(BaseSoC):
    def __init__(self, **params):
        super().__init__(**params)
        
        self.add_jtaguart()

    def add_jtaguart(self):
        from litex.soc.cores import uart
        from litex.soc.cores.jtag import JTAGAtlantic
        self.submodules.uart_phy = JTAGAtlantic()
        self.submodules.uart = uart.UART(self.uart_phy,
            tx_fifo_depth = 16,
            rx_fifo_depth = 16)
    
        self.csr.add("uart_phy", use_loc_if_exists=True)
        self.csr.add("uart", use_loc_if_exists=True)
        if self.irq.enabled:
            self.irq.add("uart", use_loc_if_exists=True)
        else:
            self.add_constant("UART_POLLING")


soc = SockitPlayground(
        sys_clk_freq             = int(100e6),
        integrated_main_ram_size = 8, # disables sdram
        integrated_rom_size      = 0x8000,
        with_uart                = False, # we add our own UART
        uart_name                = "serial")

builder = Builder(soc, csr_csv="csr.csv")
builder.build()
```
then you can fire up nios2_terminal to get the terminal output

**Comment by hansfbaier** [comment]
@somhi : Now you don't use the example above, arrow_sockit has now jtag_atlantic as default uart.
You can access it with nios2_terminal

**Comment by somhi** [comment]
Thanks Hans. I'll try it soon.
I was trying to get uart access from the on board uart through wishbone-tool https://wishbone-utils.readthedocs.io/en/latest/wishbone-tool/
Because that is what I found searching for the crossover uart.
I suggest you putting some comments about the current status of sockit target inside the python file, si people who want to try know what to expect from it.
Is anyone working on the litedram for ddr3 altera?

**Comment by hansfbaier** [comment]
Yes I put some comments in.
Whishbone won't work, because you have to connect it outside the FPGA somehow.
I am currently not aware of anyone working on ddr3.

**Comment by somhi** [comment]
It works!!!!! 
Many thanks Hans for your good job!!!
Are you planning to dive into the ddr3 issue ? 
I will give a voice to my fpga contacts.

**Comment by somhi** [comment]
By the way, I have the GPIO addon. Do you think it would be easy to use literam with one of these Mister memory modules ?
http://modernhackers.com/128mb-sdram-board-on-de10-standard-de1-soc-and-arrow-sockit-fpga-sdram-riser/

You can find my findings and projects with SoCKit here https://github.com/SoCFPGA-learning/SoCKit

**Comment by hansfbaier** [comment]
@somhi: Yes, the MiSTer memory modules are SDRAM and they are supported by liteDRAM

**Comment by hansfbaier** [comment]
Hi @somhi ,
I added support for the MiSTer SDRAM XS modules today.
Could you try it with the type of module you have?
I have a different memory chip on it, which I had to add to litedram,
but yours should work right away.
Unfortunately I can't test it so here is the code:
https://github.com/litex-hub/litex-boards/
You can test it with:
python3 litex_boards/targets/arrow_sockit.py --l2-size=0 --mister-sdram-xs-v24 --build --load
And then open nios2-terminal
and executing sdram_test
If it works, then try without the l2-size option.
Let me know how things work out.

Best regards,
Hans

**Comment by somhi** [comment]
That's impressive Hans! Unfortunately I don't have the memory module yet. Not sure which to order, but I'll buy it soon!

**Comment by hansfbaier** [comment]
Hello @somhi ,
I have this one: https://www.aliexpress.com/item/1005001733493200.html?spm=a2g0s.9042311.0.0.433c4c4duX2nvw
but its chip is not well supported by litedram yet (I just added it today, and it partly works but still has memory test errors).
This might be a great alternative, if you want more memory:
https://www.aliexpress.com/item/1005001733447375.html
But you will need  a stackable male-to-female header adapter to use it in the HPIO board.
Best regards,
Hans

**Comment by somhi** [comment]
Have you tried your module with sockit mister port? If yes, does it work? 

Maybe it's not a good idea then to buy same module if it has test errors.
Don't you think the second module with 128MB will have the same problems as the 32 one?

**Comment by hansfbaier** [comment]
Yes it works with the mister port.
But it has only 32MB.

**Comment by hansfbaier** [comment]
The 128MB will probably work better with litex because those chips are
already supported by lutedram. But wait till tomorrow I will still try a
few things.

**Comment by hansfbaier** [comment]
@somhi I just got the 32MB SDRAM module working error free and stable.
I pushed it to my fork and also submitted a pull request to the upstream project:
https://github.com/litex-hub/litex-boards/pull/170

**Comment by somhi** [comment]
That's very good news Hans! I'll order one.

BTW there is another good board at discounted price in arrow 🙂  https://www.arrow.com/en/products/deca/arrow-development-tools (use welcome promo code)

**Comment by somhi** [comment]
Hans, you're welcome to join our telegram group @Sockit_FPGA to discuss about sockit related things.

**Comment by hansfbaier** [comment]
@somhi sounds interesting, unfortunately I don't have telegram yet ...

**Pull request merged**
