### PR TITLE
sitlinv_stlv7325_v2: VCCIO jumper default factory setting is 3.3V

### PR DESCRIPTION
**Pull request by hansfbaier**

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier.

**Comment by gsomlo** [comment]
I was hoping that this missing piece might get sata and sfp ports working for me, but alas, that didn't do it either.

@hansfbaier -- do you actually have a v2 board? If so, did you have any success with its sata and/or sfp ports?

@enjoy-digital -- how about your tests on the v1 board?

**Comment by hansfbaier** [comment]
Have not tried those, and yes I have a v2 board.

**Comment by gsomlo** [comment]
> and yes I have a v2 board.

Oh, that's good to hear! :) 

I've tried both SATA ports with `--sata-gen 1` and `--sata-gen 2`, with straight-through and cross-over SATA cables (the schematic suggests the SATA ports are wired in "device", as opposed to "host" mode, suggesting cross-over would be needed to get it talking to an actual disk/device).

I've tried [this patch](https://github.com/litex-hub/litex-boards/files/11688600/litex-boards-stlv7325v2-sfp-eth-sata.patch.txt) with a Trenz SFP-SATA adapter and a Cisco gigabit Ethernet SFP, but neither ethernet nor SATA (gen1 *or* gen2) works over SFP either.

I'm wondering what (if anything) I'm missing. I have not yet heard of anyone getting SATA or SFP working (with LiteX) on either v1 or v2.

If you get a chance to test sata and/or sfp, I'd be very interested in hearing about your results...

**Comment by enjoy-digital** [comment]
@gsomlo: Sorry a bit busy with different projects/priorities. I'll try to do the test soon on V1.

**Pull request merged**
