### PR TITLE
Add support for CTUCAN for Arty & Genesys2 board

### PR DESCRIPTION
**Pull request by disdi**
This is to add support for controller area network (CAN bus) to Litex.
It is based on [CTU CAN FD IP Core](https://gitlab.fel.cvut.cz/canbus/ctucanfd_ip_core) developed by Czech Technical University in Prague.

Related MR for Litex for https://github.com/enjoy-digital/litex/pull/1900 is also raised.
Complete documentation of usage and testing can be found at [Project Wiki](https://disdi.github.io/librecar-wiki/Litex-bringup.html).

### CODE REVIEW

**Comment by disdi** [comment]
Old MR : https://github.com/litex-hub/litex-boards/pull/556

**Comment by enjoy-digital** [comment]
Thanks @disdi, that's merged and I'll adapt to https://github.com/enjoy-digital/litex/pull/2007.

**Comment by enjoy-digital** [comment]
Updated with https://github.com/litex-hub/litex-boards/commit/15c6f89b1a75c8dda50fb6b8ad1f139e728a78bf.

**Comment by disdi** [comment]
Thanks @enjoy-digital for taking this in.

**Pull request merged**
