### PR TITLE
beaglewire platform and target added

### PR DESCRIPTION
**Pull request by ombhilare999**
Added beaglewire platform and target file.
- Platform file for beaglewire can be found [here](https://github.com/litex-hub/litex-boards/blob/db9c98b28afcb64058662ff254f465cd63ff6a2a/litex_boards/platforms/beaglewire.py)
- Target file for beaglewire can be found [here](https://github.com/litex-hub/litex-boards/blob/db9c98b28afcb64058662ff254f465cd63ff6a2a/litex_boards/targets/beaglewire_crossover.py)
- Detailed guide for how to use the beaglewire litex can be found [here](https://beaglewire.github.io/Blogs/BeagleWire-Litex.html)

Demo of working litex on beaglewire with uart wb crossover: https://www.youtube.com/watch?v=mx4KWYq29I0

kindly review it and let me know if any changes are required. 

regards,
omkar bhilare
ombhilare999@gmail.com

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @ombhilare999 and nice demo! This looks fine and has been merged. I just did minor changes on top of it for consistency with the other boards:
- https://github.com/litex-hub/litex-boards/commit/35df77258a1f81b9c5f3a48ceef7ec5d6d5f217a
- https://github.com/litex-hub/litex-boards/commit/ce254208ffbccecf58b8578bbe8fac1b07290703

You should be able to build a design similar to the one used in your demo with: `./quertyembedded_beaglewire.py --cpu-type=serv --uart-name=crossover+bridge --build`

**Comment by mwelling** [comment]
My company name is QWERTY Embedded Design LLC, like the keyboard but this design belongs to the community.

**Comment by enjoy-digital** [comment]
@mwelling: Sorry for the typo, this is fixed with https://github.com/litex-hub/litex-boards/commit/ce52c8c5edbdb2dbc86f153e06d3abdd1cb3dad5.

**Comment by mwelling** [comment]
Thanks!

**Pull request merged**
