### PR TITLE
Added Arty S7 board

### PR DESCRIPTION
**Pull request by Fatsie**
As the pin-out is totally different from the A7 board I did put this
in a separate class and not as a variant of the Arty board.
Used migen Arty S7 board file and Digilent xdc file as reference.

### CODE REVIEW

**Comment by mithro** [comment]
FYI - OpenOCD has support for Arty S7 - http://openocd.zylin.com/gitweb?p=openocd.git;hb=refs%2Fchanges%2F25%2F4525%2F3;f=tcl%2Fboard%2Farty_s7.cfg

I believe @cr1901 was playing with this board.

**Comment by cr1901** [comment]
@mithro It took them a while to merge, but arty s7 should work out-of-the-box on upstream OpenOCD: http://openocd.zylin.com/#/c/4525/

**Comment by enjoy-digital** [comment]
@Fatsie: thanks, we could merge it but we should probably fix the copyrights first. I think @cr1901 contribute the original platform support (https://github.com/m-labs/migen/commit/0aa76fa37f07641c6a95a064e0f5cd62e470b514#diff-61185eba260ac71a6f131f64562607e5) so the copyrights for the platform should probably be:
````
# This file is Copyright (c) 2018 William D. Jones <thor0505@comcast.net>
# This file is Copyright (c) 2020 Staf Verhaegen <staf@fibraservi.eu>
# License: BSD
````
Can you fix this and we could merge it?

**Comment by Fatsie** [comment]
As it is merged I assume copyright was OK. Feel free to fix it on main branch if still changes wanted.

**Comment by enjoy-digital** [comment]
@Fatsie: yes thanks, i just merged it and did the minor changes to it with https://github.com/litex-hub/litex-boards/commit/52c9648176c7e04d6375536b5ecc9e04db259b96. I'm going to look at the Linux-on-LiteX-VexRiscv PR now.

**Pull request merged**
