### PR TITLE
Add board support for Terasic/Arrow DECA board (Intel Max10)

### PR DESCRIPTION
**Pull request by hansfbaier**
Hi I just added support for this board.

### CODE REVIEW

**Comment by hansfbaier** [comment]
```
$ nios2-terminal 
nios2-terminal: connected to hardware target using JTAG UART on cable
nios2-terminal: "Arrow MAX 10 DECA [7-4.6]", device 1, instance 0
nios2-terminal: (Use the IDE stop button or Ctrl-C to terminate)


        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2020 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on Feb 25 2021 11:51:26
 BIOS CRC passed (6949b5c9)

 Migen git sha1: --------
 LiteX git sha1: --------

--=============== SoC ==================--
CPU:		VexRiscv @ 50MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		32KiB
SRAM:		8KiB

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
Timeout
No boot medium found

--============= Console ================--

litex> 
```

**Comment by enjoy-digital** [comment]
Great, thanks @hansfbaier! I should also receive one in the next days, this board is cheap but seems very capable.

**Comment by hansfbaier** [comment]
@enjoy-digital Thank you for the quick response. Yes the board is insane value for money. The introductory price (and IMO the unsibsidized price) was $160ish, so it is insane value for money. Especially when you consider the parts on it.

**Comment by pcotret** [comment]
@hansfbaier, there's a typo in the boards table 😉 
16-bit 512M**G** DDR3 instead of 16-bit 512MB DDR3

**Comment by hansfbaier** [comment]
@pcotret Thanks! Just created a pull request: https://github.com/litex-hub/litex-boards/pull/182

**Pull request merged**
