### PR TITLE
Add support for SDI-MIPI Video Converter

### PR DESCRIPTION
**Pull request by apokusinski**
This PR adds target and platform for Antmicro's open-source [SDI-MIPI Video Converter](https://github.com/antmicro/sdi-mipi-video-converter).

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @apokusinski, can you make sure to add Antmicro copyrights, make sure to fix some ident issues (probably space vs tabs issues)? and we'll be able to merge.

**Comment by apokusinski** [comment]
@enjoy-digital I fixed formatting and added Antmicro copyrights. Hope it's ok now

**Comment by enjoy-digital** [comment]
Thanks @apokusinski for the changes, this is merged.

**Comment by enjoy-digital** [comment]
@apokusinski: I just did minor cleanup/updates with https://github.com/litex-hub/litex-boards/commit/7b716e489961496f9b2a0852cbaf67a49fc0110f.

**Pull request merged**
