### PR TITLE
Support for "discontinued" Avnet aes-ku040-db-g development board

### PR DESCRIPTION
**Pull request by AEW2015**
Not all interfaces are currently supported. 

Here are related documents:
https://www.avnet.com/opasdata/d120001/medias/docus/13/aes-AES-KU040-DB-G-User-Guide.pdf
https://www.avnet.com/opasdata/d120001/medias/docus/13/aes-AES-KU040-DB-G-Schematics.pdf

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @AEW2015! This looks good. Can you just update the copyrights (use yours on the platform and target) and share the validation status: Are the Ethernet/DRAM working?

**Comment by AEW2015** [comment]
We ran Linux on Litex for it last year, but I haven't tested it recently with updated Litex repos.  I will retest and get a screenshot.

**Comment by AEW2015** [comment]
I having issues with litex-boards not loading the new module:
Traceback (most recent call last):
  File "./xilinx_aesku40.py", line 15, in <module>
    from litex_boards.platforms import aesku40
ImportError: cannot import name 'aesku40'

What is the correct way to install the dev fork to find these new files?

**Comment by AEW2015** [comment]
I boot it over serial just fine, but the tftpboot is only receiving 512 bytes per request.
I there an issue with my tftp server?

```
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB
   Read: 0x40000000-0x40200000 2.0MiB
Memtest OK
Memspeed at 0x40000000 (Sequential, 2.0MiB)...
  Write speed: 206.0MiB/s
   Read speed: 101.5MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
             Timeout
Booting from SDCard in SD-Mode...
Booting from boot.json...
Booting from boot.bin...
SDCard boot failed.
Booting from network...
Local IP: 169.254.132.50
Remote IP: 169.254.132.100
Booting from boot.json...
Copying Image to 0x40000000... (512 bytes)
Copying rv32.dtb to 0x40ef0000... (512 bytes)
Copying rootfs.cpio to 0x41000000... (512 bytes)
Copying opensbi.bin to 0x40f00000... (512 bytes)
Executing booted program at 0x40f00000

--============= Liftoff! ===============--
```

**Comment by AEW2015** [comment]
Switch from tftp with xinetd to  tftpd-hpa and it works!
Let me do some copywrite and name changes... 
```
Welcome to Buildroot
buildroot login: root
                   __   _
                  / /  (_)__  __ ____ __
                 / /__/ / _ \/ // /\ \ /
                /____/_/_//_/\_,_//_\_\
                      / _ \/ _ \
   __   _ __      _  _\___/_//_/         ___  _
  / /  (_) /____ | |/_/__| | / /____ __ / _ \(_)__ _____  __
 / /__/ / __/ -_)>  </___/ |/ / -_) \ // , _/ (_-</ __/ |/ /
/____/_/\__/\__/_/|_|____|___/\__/_\_\/_/|_/_/___/\__/|___/
                  / __/  |/  / _ \
                 _\ \/ /|_/ / ___/
                /___/_/  /_/_/
  32-bit RISC-V Linux running on LiteX / VexRiscv-SMP.

login[72]: root login on 'console'
root@buildroot:~#
```

**Comment by enjoy-digital** [comment]
Thanks @AEW2015, this looks good now and has been merged.

**Pull request merged**
