### PR TITLE
Add support for QMTech 5CEFA2 board (Cyclone V)

### PR DESCRIPTION
**Pull request by hansfbaier**
A new board arrived!
```
        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2021 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on Nov  5 2021 09:48:15
 BIOS CRC passed (cfd8447f)

 Migen git sha1: 7507a2b
 LiteX git sha1: 9ecb1e61

--=============== SoC ==================--
CPU:		VexRiscv @ 75MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		128KiB
SRAM:		8KiB
L2:		8KiB
SDRAM:		32768KiB 16-bit @ 75MT/s (CL-2 CWL-2)

--========== Initialization ============--
Initializing SDRAM @0x40000000...
Switching SDRAM to software control.
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB     
   Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK
Memspeed at 0x40000000 (Sequential, 2.0MiB)...
  Write speed: 16.2MiB/s
   Read speed: 19.2MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
             Timeout
No boot medium found

--============= Console ================--

litex> 
```
The CPU would run at well over 100MHz, but the RAM only goes up to 75MHz.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier! (Psst, not sure I should say it..., but I think you are also addicted to new FPGA boards :))

**Comment by hansfbaier** [comment]
@enjoy-digital There is no denying it... It *is* addictive. I console myself that at least it has a use for the community.
Actually with the QMTech boards it also has a practical use. I evaluate different FPGAs for my audio interface.
At least that's what I am telling myself :D

**Comment by dgacina** [comment]
Hi there, is there a support for QMTech 5CEFA5  (the more expensive QM's Cyclone V) board?

**Comment by hansfbaier** [comment]
@dgacina  I just had a look at the schematic, and, unfortunately those are not pin compatible like the Cyclone IV boards.
So I would have to make a new one. I would gladly make one for a hardware donation of a 5CEFA5 board :D
Alternatively you could take the schematic and the existing 5CEFA2 files and fill in the different Pin names accordingly.

**Comment by dgacina** [comment]
Can you please elaborate a bit, what is not compatible with what? I am about to order that 5CEFA5 board, so if possible I would like to contribute to this project.

**Comment by hansfbaier** [comment]
@dgacina If you look at the schematic https://github.com/ChinaQMTECH/QM_CYCLONE_V/blob/master/5CEFA5F23/Hardware/5cefa5-sdram-20200910-V01.pdf
You see that for example board headers are connected to FPGA pins.
FPGA pins have names with a combination of letters and numbers:
image
What you have to do is to copy those pin names into the platform file:
https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/qmtech_5cefa2.py
If you compare the schematic to that of the 5CEFA5F23, you will notice the pin names are different from the 5CEFA5.
This is not the case for Cyclone IV, where larger chips have exactly the same pinout and thus we can use the same platform file.
So what you need to do is:
1. copy the qmtech_5cefa2.py platform file to a new file
2. remove all the pin names from the file
3. copy all the new pin names from the schematic PDF in there
4. copy also https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/qmtech_5cefa2.py
5. and edit the chip names in there and that it references the new platform file
Put this into your own fork of litex-boards and do as much as you can, and if you get stuck, drop me a note, I can answer your questions

**Pull request merged**
