### PR TITLE
Add de10 nano board

### PR DESCRIPTION
**Pull request by sajattack**
I'm not really sure what I'm doing here at all. I wrote this, ran the targets/de10nano.py, that generated an rbf, which I uploaded to the de10 nano, and it echoes back serial. Does that sound about right?

### CODE REVIEW

**Comment by sajattack** [comment]
I added the ddram pins, but not sure how to set it up on the target side.

**Comment by enjoy-digital** [comment]
Thanks @sajattack, have you been able to get the LiteX bios prompt?

**Comment by sajattack** [comment]
How do I do that?

**Comment by sajattack** [comment]
```
b'help\n\rLiteX BIOS, available commands:\n\rmr         - read address space\n\rmw         - write address space\n\rmc         - copy address space\n\r\n\rcrc        - compute CRC32 of a part of the address space\n\rident      - display identifier\n\r\n\rreboot     - reset processor\n\rserialboot - boot via SFL\n\r\n\r\x1b[92;1mlitex\x1b[0m> '
```
Got it!

**Comment by sajattack** [comment]
Ready for review.

**Comment by sajattack** [comment]
Linux proven :tada: https://hastebin.com/ayonevufam.cs

**Comment by enjoy-digital** [comment]
Thanks for the PR and results, it's merged with minor changes:
https://github.com/litex-hub/litex-boards/commit/cf9a9ff91b3a5613d5419fb5aa83e073052b0302
https://github.com/litex-hub/litex-boards/commit/0627f55dca2dd3fd53504017fb4c2c61374e3454
Happy to merge the Linux-on-LiteX-Vexriscv changes too, you will just have to rename SDRAMSoC to MiSTerSDRAMSoC.

**Pull request merged**
