### PR TITLE
Spartan Edge Accelerator Board support

### PR DESCRIPTION
**Pull request by primeshp**
Created a new Spartan Edge Accelerator board. https://www.seeedstudio.com/Spartan-Edge-Accelerator-Board-p-4261.html?gclid=Cj0KCQiA2sqOBhCGARIsAPuPK0hrq-NQxOUmlCJjS-m6wdFDXbhP-a_JoKUqX8sp4p5J4_AOh-k0GnMaAhzLEALw_wcB

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @primeshp, this is a very interesting board to start with FPGAs and I wasn't aware of it (I just ordered one). The initial support looks good, I'm going to merge it and just do minor changes to it.

**Comment by enjoy-digital** [comment]
I just did some minor cleanup in top of your commits in https://github.com/litex-hub/litex-boards/commit/28cdc8b9147fcccff50cefa080945201ee78a64a to ease have something more consistent with the other boards and simplify future maintenance. Thanks for the initial PR, nice to see the recently added NeoPixel core is already useful on boards with NeoPixel Leds. I'll play with it when I'll receive mine.

**Comment by primeshp** [comment]
Thanks.

One thing I noticed is that you changed the file name
to seeedstudio_spartan_edge_accelerator.py. If you do that I think the file
under target needs to modify to reflect that with following changes

instead of
from litex_boards.platforms import spartan_edge_accelerator
platform = spartan_edge_accelerator.Platform()
replace with from litex_boards.platforms import  seeedstudio_
spartan_edge_accelerator
platform = seeedstudio_spartan_edge_accelerator.Platform()
thanks

Primesh

**Comment by enjoy-digital** [comment]
Thanks @primeshp for the feedback, in fact the vendor can be automatically discovered since added to the list of vendor, so current scripts work (and follow the approach used on the other boards).

**Pull request merged**
