### PR TITLE
sockit: Add an option to plug in an UART via the GPIO daughter board, make connector pin numbers one-based

### PR DESCRIPTION
**Pull request by hansfbaier**
jtag_atlantic is too slow to upload larger binaries.
We need a physical uart option.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier, it could be done more easily with
- Adding `gpio_serial` pins to the platform.
- Just using `./target.py --uart-name=gpio_serial` to select the `gpio_serial ` instead of JTAG?

Would you mind doing the changes on this?

**Review by enjoy-digital — CHANGES_REQUESTED** [review]
Thanks @hansfbaier, it could be done more easily with
- Adding `gpio_serial` pins to the platform.
- Just using `./target.py --uart-name=gpio_serial` to select the `gpio_serial ` instead of JTAG?

Would you mind doing the changes on this?

**Comment by hansfbaier** [comment]
@enjoy-digital OK, I made the changes and rebased my branch to newest upstream.
I was not aware that add_uart automatically requests the uart name pins, and this is more elegant, yes.
Although not as explicit for the user.
(He will have to look at the source code to find out which uart name to choose)

**Comment by hansfbaier** [comment]
@enjoy-digital The requested changes are ready for review.

**Review by enjoy-digital — APPROVED** [review]
Thanks @hansfbaier, this looks good.

**Pull request merged**
