### PR TITLE
muselab_icesugar: first basic version which boots

### PR DESCRIPTION
**Pull request by hansfbaier**
```
        __   _ __      _  __
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2021 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on May  7 2021 10:13:57
 BIOS CRC passed (21e99d4b)

 Migen git sha1: 3ffd64c
 LiteX git sha1: d6084cd1

--=============== SoC ==================--
CPU:		VexRiscv_Lite @ 24MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		32KiB
SRAM:		64KiB

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
             Timeout
No boot medium found

--============= Console ================--

litex> ident
Ident: LiteX SoC on Muselab iCESugar 2021-05-07 11:41:55
```
Flash and load work well.
MusLab LED pmod also works well.

### CODE REVIEW

**Comment by hansfbaier** [comment]
The CI test fails, because this code depends on: https://github.com/enjoy-digital/litex/pull/905
which is not merged yet.

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier, this is merged.

**Comment by enjoy-digital** [comment]
I just modified the comments a bit to make them more impersonal: https://github.com/litex-hub/litex-boards/commit/e99272cb07d6957ecb83bc49938d49aa7d7e81d3

**Comment by hansfbaier** [comment]
OK thanks!

**Pull request merged**
