### PR TITLE
Enable use of HalfRateGENSDRPHY on de10nano

### PR DESCRIPTION
**Pull request by rob-ng15**
Add Misc("") tags, provides stability for the SDRAM to allow use of HalfRateGENSDRPHY

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Great, thanks for testing and doing the PR, i was going to do some test on Intel/Altera in the next days. You were not able to get it working without the additional Misc constraints?

**Comment by rob-ng15** [comment]
Hi there,

To be honest I didn't try. I've been running with them for a while as those
constraints are in the MiSTer definitions.

Rob.

**Comment by enjoy-digital** [comment]
Thanks, would you mind doing a test without? (just testing with the old Platform file) I'd like to keep things similar between the different boards to ease maintenance, so if this is not strictly needed, i'd like to avoid them (or apply them to the others boards if mandatory).

**Comment by enjoy-digital** [comment]
This has been merged and the IO constraints have been simplified a bit for consistency with the others platforms with https://github.com/litex-hub/litex-boards/commit/b4b1ab8621e26a0e84b34f755a3695e451969d84. Could you do a test with it and report your results?

**Comment by rob-ng15** [comment]
Hi there,

Will do.

Rob.

**Comment by rob-ng15** [comment]
Hi there,

Get memory errors with the changes that were made to my patch. It works
with:


_mister_sdram_module_io = [
    ("sdram_clock", 0, Pins("AD20"), IOStandard("3.3-V LVTTL")),
    ("sdram", 0,
        Subsignal("cke", Pins("AG10")),
        Subsignal("a",   Pins(
            "Y11 AA26 AA13 AA11 W11 Y19 AB23 AC23",
            "AC22 C12 AB26 AD17 D12")),
        Subsignal("dq",  Pins(
            "E8    V12 D11  W12 AH13  D8 AH14 AF7",
            "AE24 AD23 AE6 AE23 AG14 AD5  AF4 AH3"),
            Misc("FAST_OUTPUT_ENABLE_REGISTER ON"),
            Misc("FAST_INPUT_REGISTER ON")),
        Subsignal("ba",    Pins("Y17 AB25")),
        Subsignal("cas_n", Pins("AA18")),
        Subsignal("cs_n",  Pins("Y18")),
        Subsignal("ras_n", Pins("W14")),
        Subsignal("we_n",  Pins("AA19")),
        Misc("CURRENT_STRENGTH_NEW \"MAXIMUM CURRENT\""),
        Misc("FAST_OUTPUT_REGISTER ON"),
        Misc("ALLOW_SYNCH_CTRL_USAGE OFF"),
        IOStandard("3.3-V LVTTL")
    ),


Rob.

**Comment by enjoy-digital** [comment]
Thanks for the feedback, would you mind testing with https://github.com/litex-hub/litex-boards/commit/7399d13cefe88126e60549763ddb0dde85cbc02f? If not working, i'll update with the sddram constraints you just provided.

**Comment by rob-ng15** [comment]
Hello there,

Sadly, that failed to work.

Rob.

**Comment by enjoy-digital** [comment]
Sorry, with https://github.com/litex-hub/litex-boards/commit/9730c6f7221283752bd8662bd402a384183d7a38 it should now be using the constraints you already tested.

**Comment by rob-ng15** [comment]
Thanks.

**Comment by rob-ng15** [comment]
Hello,

A later change has broken compilation. I had to change it to this:


        # SDR SDRAM
--------------------------------------------------------------------------------
        if with_mister_sdram and not self.integrated_main_ram_size:
            self.submodules.sdrphy =
HalfRateGENSDRPHY(platform.request("sdram")) if sdram_rate == "1:2" else
GENSDRPHY(platform.request("sdram"))
            self.add_sdram("sdram",
                phy                     = self.sdrphy,
                module                  = AS4C32M16(sys_clk_freq,
sdram_rate),
                origin                  = self.mem_map["main_ram"],
                size                    = kwargs.get("max_sdram_size",
0x40000000),
                l2_cache_size           = kwargs.get("l2_size", 8192),
                l2_cache_min_data_width = kwargs.get("min_l2_data_width",
128),
                l2_cache_reverse        = True
            )



This line:

sdrphy_cls = HalfRateGENSDRPHY if sdram_rate == "1:2" else GENSDRPHY

combined with this line:

phy = self.sdrphy,

was giving an error.


Error introduced by
https://github.com/litex-hub/litex-boards/compare/9730c6f722...760b8ff93a

Rob.

**Pull request merged**
