### PR TITLE
faster sdcard boot on 2.0

### PR DESCRIPTION
**Pull request by goran-mahovlic**

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Great thanks @goran-mahovlic, have you got it running with this change and Linux-on-LiteX-Vexriscv?

**Comment by goran-mahovlic** [comment]
> Great thanks @goran-mahovlic, have you got it running with this change and Linux-on-LiteX-Vexriscv?

Yes I have checked on 3.1.7 board and it is working much faster

**Comment by goran-mahovlic** [comment]
I will try again later as now I need to go to Radiona

**Comment by enjoy-digital** [comment]
@goran-mahovlic: Perfect thanks, so it was related to a change of the `wifi_gpio0 ` I guess?

**Comment by enjoy-digital** [comment]
(Sorry, wrong button...)

**Comment by goran-mahovlic** [comment]
> @goran-mahovlic: Perfect thanks, so it was related to a change of the `wifi_gpio0 ` I guess?

I think it is both wifi_gpio0 and commenting unused pins

**Comment by enjoy-digital** [comment]
This is merged, thanks @goran-mahovlic!

**Pull request merged**
