### PR TITLE
Initial support for STLV7325 (v2) Kintex-7 board.

### PR DESCRIPTION
**Pull request by gsomlo**
This is the 2nd (2023) version of the board sold through https://www.aliexpress.us/item/3256801088848039.html

Link to the vendor-provided schematic: [XC7K325TFFG676-2原理图.pdf](https://github.com/litex-hub/litex-boards/files/11301409/XC7K325TFFG676-2.pdf)

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @gsomlo! Do you know if there are lots of differences between the two revisions of the boards or if only a few IOs that are changes? If the latter, this could be worth trying to merge v1 and v2 platforms/targets in a single file as we are doing for some other boards (ex OrangeCrab, ColorLight, etc...).

**Comment by gsomlo** [comment]
@enjoy-digital -- I force-pushed an updated version. Have a look (diff the platform files and see how many pins are different, and how you feel about trying to make things conditional vs. just using a separate pair of board & target files).

Off the top of my head:
- the 100MHz clock is now a 50MHz clock
- gmii ethernet is now rgmii
- hdmi has fewer connected pins
- external BTB interface has a bunch of additional pins connected
- many of the interfaces have *some* of the pins changed from v1

LMK what you think.

**Comment by enjoy-digital** [comment]
Hi @gsomlo,

this new revisions indeed seems quite different. I'm fine with a different platform/target then since merging the two will make things more difficult to follow/understand.

**Comment by gsomlo** [comment]
RGMII Ethernet, UART, microSD card, and (1G included) DDRAM successfully tested and working with litex.

Not working: SATA

Not tested: SFP, HDMI, FMC/LPC, other external connectors

NOTE: on FMC/LPC, ***none*** of the `DP0*` pins are connected to the FPGA, which precludes using an ***external*** SATA adapter such as e.g. the [AB09-FMCRAID](https://www.dgway.com/AB09-FMCRAID_E.html)

**Pull request merged**
