### PR TITLE
alinx_axau15: Added new Alinx Artix US+ board

### PR DESCRIPTION
**Pull request by Johnsel**
https://alinx.com/en/detail/691

Docs: https://alinx.com/public/upload/file/AXAU15_UG.pdf
English Docs: https://file.io/w0Kc2qJPkABm

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @Johnsel, I'm merging and will do probably do some changes while doing a closer review.

**Comment by tommythorn** [comment]
@Johnsel this look interesting, but unfortunately the Englist docs link appears to have been deleted.  Do you have a different pointer?

**Comment by Johnsel** [comment]
[Alinx AXAU15 User Manual REV1.0.pdf](https://github.com/litex-hub/litex-boards/files/13834341/Alinx.AXAU15.User.Manual.REV1.0.pdf)
@tommythorn see above

**Comment by tommythorn** [comment]
Brilliant, thanks a bunch.

**Comment by Johnsel** [comment]
@tommythorn Note that there are a few errors in the documentation, e.g. GTH is 16.3Gbps not 12.5Gbps and the chip supports PCIe4.0 as well.

**Pull request merged**
