### PR TITLE
[init] added colorlight i9+ based on XC7A50 FPGA

### PR DESCRIPTION
**Pull request by chmousset**
The [Colorlight i9+](https://controller-led.com/products/colorlight-i-series-led-display-controller-i9-i6-i5-led-receiving-card) is another LED receiver card, but contrary to the i5 family, this one is based on an ARTIX 7 FPGA.

It has some similarities with the i9 (same PHY and SDRAM) but a bigger FPGA and more available IOs.

**Todo**
- [x] test Ethernet 1 (U9, SDIO PHY id 1) : done. Etherbone & ping works.
- [x] test Ethernet 0 (U5, SDIO PHY id 0)
- [x] test SDRAM

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Nice @chmousset, this looks interesting! Do you want to merge now or do you first want to validate the Ethernet 0 and SDRAM?

**Comment by chmousset** [comment]
@enjoy-digital I think it's better waiting for me to validate the SDRAM. unfortunately my i9+ reballing has most likely failed. I need to reball it properly to finish the tests.

**Comment by chmousset** [comment]
Test are done, everything works!
This PR can be merged.

```
       / /  (_) /____ | |/_/
      / /__/ / __/ -_)>  <
     /____/_/\__/\__/_/|_|
   Build your hardware, easily!

 (c) Copyright 2012-2022 Enjoy-Digital
 (c) Copyright 2007-2015 M-Labs

 BIOS built on Apr 30 2023 16:49:11
 BIOS CRC passed (d65378b8)

 LiteX git sha1: 3dee741b

--=============== SoC ==================--
CPU:            VexRiscv @ 100MHz
BUS:            WISHBONE 32-bit @ 4GiB
CSR:            32-bit data
ROM:            128KiB
SRAM:           8KiB
L2:             8KiB
SDRAM:          8192KiB 32-bit @ 100MT/s (CL-2 CWL-2)

--========== Initialization ============--
Initializing SDRAM @0x40000000...
Switching SDRAM to software control.
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2.0MiB)...
  Write: 0x40000000-0x40200000 2.0MiB     
   Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK
Memspeed at 0x40000000 (Sequential, 2.0MiB)...
  Write speed: 33.6MiB/s
   Read speed: 50.5MiB/s

--============== Boot ==================--
Booting from serial...
Press Q or ESC to abort boot completely.
sL5DdSMmkekro
             Timeout
No boot medium found

--============= Console ================--

litex> 

```

**Comment by enjoy-digital** [comment]
Great, thanks @chmousset!

**Pull request merged**
