### PR TITLE
sipeed_tang_nano_9k: new board

### PR DESCRIPTION
**Pull request by Icenowy**
Add a new board based on GW1N(R), which is Sipeed Tang Nano 9K.

The PSRAM built in cannot be utilized yet, and all display output isn't tested by me now due to lack of hardware.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Great, thanks! I should receive mine in a few days and was planning to do the support, I'll just do the test then :) (and could test the untested features).

**Comment by enjoy-digital** [comment]
I just fixed the copyrights/description in the platform with https://github.com/litex-hub/litex-boards/commit/e35b9b439f667e4e6a8870c47bcabf1f8f30f655.

**Comment by Icenowy** [comment]
> Great, thanks! I should receive mine in a few days and was planning to do the support, I'll just do the test then :) (and could test the untested features).

By the way to test you will need newest openFPGALoader, in which a PR to add GW1N-9C is jist added.

**Comment by enjoy-digital** [comment]
Thanks, I indeed saw the openFPGALoader PR.

**Pull request merged**
