### PR TITLE
Initial release for Snickerdoodle

### PR DESCRIPTION
**Pull request by derekmulcahy**
Basic files for Snickerdoodle support. The target file downloads a basic XCI file by default. This can be overridden using the **--xci-file** option. I also added a **--target** option to specify the programmer hardware target.  I am not sure what would need to be done to support the XC7Z020 used in the Snickerdoodle Black.

snickerdoodle_ps7

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @derekmulcahy, this looks good. For maintenance, I would prefer that we do the Zynq/Led integration in a similar way we are doing on other targets. Please tell me if you prefer that  I do it.

**Comment by derekmulcahy** [comment]
@enjoy-digital I incorporated some changes after reviewing the recently checked in digilent-arty-z7 files. These files should now pass the CI tests. I hope the rewrite is better and not more work! Feel free to edit as you see fit. Thanks for Litex!!!

**Comment by derekmulcahy** [comment]
LedChaser works fine with just one LED so I switched to code to use it.

**Comment by enjoy-digital** [comment]
Thanks @derekmulcahy, this has been merged. I did minor changes on top:
- https://github.com/litex-hub/litex-boards/commit/dc61d383e6babad0cbad7f5c8029f69c78be20f9
- https://github.com/litex-hub/litex-boards/commit/c9816f2bc1d3230f1e412505433cd626cc9eb392

I also have this board and will try to play a bit more with it in the future.

**Comment by derekmulcahy** [comment]
Looks great, built and works for me, thanks.

**Pull request merged**
