### PR TITLE
Add support for NetFPGA-Sume

### PR DESCRIPTION
**Pull request by GustavsC**
Tasks:

- [x] LedChaser/Buttons/Cpu Reset
- [x]  UART/Serial
- [x] 4 GiB Memory 
- [x] 4x SFP Ethernet
- [ ] I2C (Bug: "Couldn't read SDRAM size from the SPD")
- [x] Create_programmer
- [x] Update memory support to 8GiB (Use 2 memory slots instead of 1)

Tests with CPUs (125Mhz):

- [x] Rocket - Linux
- [x] Rocket - Full
- [x] Vexriscv - Standard (Memory Overlap, but should work if revised).

Screenshot from 2024-08-19 21-00-21

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Nice! Thanks for the detailed status/progress. Happy to review it when you think it's ready.

**Comment by GustavsC** [comment]
Good morning!
I believe that is worth reviewing. SFP+ and SDCard enabled.
 
Just for some clarification, NetFPGA Sume is Virtex7 FPGA with GTH Transceivers. Looking in the LiteX repositories (liteeth and liteiclink) I only see support for Ultrascales, Artix7, and Kintex7 (correct if I'm wrong), so I added support for Virtex7 GTH using Kintex 7 GTX transceivers as a base.

All these updates are in forked repositories:
https://github.com/GustavsC/liteiclink/blob/master/liteiclink/serdes/gth_7series_init.py
https://github.com/GustavsC/liteiclink/blob/master/liteiclink/serdes/gth_7series.py
https://github.com/GustavsC/liteeth/blob/master/liteeth/phy/v7_1000basex.py

**Tests**:
I only tested with Rocket and VexRiscv, and it seems to be working well:

Rocket Full/Linux dont work with frequencies below 75MHz.

| SoC / Frequency (MHz) | 50 | 75 | 100 | 125|
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Rocket Full  | X  | Ok  | Ok  | Ok  |
| Rocket Linux  | X  | Ok  | Ok  | Ok  |
| VexRiscv Standard | Ok  | Ok  |  Ok  | Ok  |

To make sure of the tests, i tried booting Linux on the SoC: 

- digilent_netfpga_sume.py --build --cpu-type rocket --cpu-variant linux --cpu-mem-width 8 --with-sdcard --with-ethernet

Successfully booted:
Screenshot from 2024-09-17 12-21-00
Screenshot from 2024-09-17 12-25-52

DeviceTree used: https://github.com/GustavsC/linux-on-litex-rocket/blob/master/conf/digilent_netfpga_sume.dts

**Comment by enjoy-digital** [comment]
Thanks @GustavsC for the update, this looks good! We can merge and could also probably merge the LiteICLink/LiteEth changes if you want to create a PR.

**Comment by enjoy-digital** [comment]
Thanks a lot @GustavsC for the different PRs, I just merged the LiteEth/LiteICLink PRs and we can now merge this one :)
Very nice work, the NetFPGA-Sume seems to be a really capable board! (Wanted to have one in the past but haven't yet had the occasion to justify the purchase :)).

**Pull request merged**
