### PR TITLE
fixed missing "trenz_" prefix

### PR DESCRIPTION
**Pull request by AnttiLukats**
build succeeds now.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks. The Max1000 board support has been integrated and minor modification have been done to it to uniformize it with https://github.com/litex-hub/litex-boards/commit/caac75c7dbcba68d9f4fb948107cb5d6ff60e05f.

The `trenz_` prefix is not required and is handled directly by https://github.com/litex-hub/litex-boards/blob/master/litex_boards/__init__.py. This is probably related to an installation issue/update on your machine, please be sure to run again `python3 setup.py develop (or install)`.

**Comment by AnttiLukats** [comment]
Thanks! I kind of not understand the meaning of the prefix or the lack of it, well it seems the prefix should NOT be used, right?

**Comment by enjoy-digital** [comment]
The prefix has been added to the filenames (to ease cleanup platforms/targets directories), but this is optional in the imports. (to keep retro-compatibility but also to ease imports).

**Comment by AnttiLukats** [comment]
yes, thanks again all understood now.

**Pull request closed without merging**
