### PR TITLE
qmtech_artix7_fgg676.py: This board also has a 200T variant

### PR DESCRIPTION
**Pull request by hansfbaier**
I just encountered a 200T variant of this board in the wild.
Which means it exists.
A MiSTeX user has it.

### CODE REVIEW

**Comment by hansfbaier** [comment]
Yes they do, this has been verified

**Comment by tommythorn** [comment]
"kgates can only be 75 or 100 representing" you forgot to include 200 here.

**Comment by hansfbaier** [comment]
@tommythorn I think I did 
20240510_05h11m27s_grim

**Comment by hansfbaier** [comment]
@tommythorn Ah, you mean the comment, yes.

**Comment by hansfbaier** [comment]
@tommythorn OK, fixed. Thanks.

**Comment by enjoy-digital** [comment]
Thanks @hansfbaier!

**Pull request merged**
