### PR TITLE
DECA: Add Ethernet and Etherbone support

### PR DESCRIPTION
**Pull request by jevinskie**
Based on top of #341 and #342.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Great, thanks @jevinskie! I however need to have one PR per functionnality otherwise things get complicated to review/merge. Can you limit this PR to JTAG? And open another one with Ethernet/Etherbone support on DECA (but without the LITEX_DEFAULT_IP change)? Thanks.

**Comment by enjoy-digital** [comment]
@jevinskie: Sorry I got confused; I just saw JTAG support was another PR. I'll just pick https://github.com/litex-hub/litex-boards/pull/343/commits/f6f279122a3313da1bd6bdd19172c0393e319918 from this PR and we'll discuss the LITEX_DEFAULT_IP later.

**Comment by jevinskie** [comment]
Cleaned up to apply standalone to the main branch.

**Comment by enjoy-digital** [comment]
Thanks @jevinskie, this has been merged and tested succesfully.

**Pull request merged**
