### PR TITLE
Add FPC-III board support.

### PR DESCRIPTION
**Pull request by garytwong**
Please note this depends on https://github.com/enjoy-digital/litevideo/pull/36 and https://github.com/enjoy-digital/litex/pull/787.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Thanks @garytwong, do you have more information about this board?

**Comment by garytwong** [comment]
I haven't really published anything beyond the notes accompanying the schematics (see https://repo.or.cz/fpc-iii.git, cited in 25d6bcb346bc4bc89b7467650f86db99abe1a439).  But I'm happy to answer questions on anything that needs clarification!

**Comment by enjoy-digital** [comment]
OK thanks, sorry I just saw it was in the commit log. We could merge the platform and base SoC support (with CPU, DDR3, Ethernet) but the video/keyboard part is a bit too specific for the application and bit out of scope for LiteX/LiteVideo (we are trying to provide generic cores, specific cores are integrated separately in application projects). So would it work for you to integrate only the BaseSoC with CPU, DDR3, Ethernet to LiteX-Boards and handle Video/Keyboard in your project? (eventually reusing BaseSoC as a base)?

**Comment by garytwong** [comment]
> the video/keyboard part is a bit too specific for the application and bit out of scope for LiteX/LiteVideo

Yes, I agree.

> So would it work for you to integrate only the BaseSoC with CPU, DDR3, Ethernet to LiteX-Boards and handle Video/Keyboard in your project?

In principle, definitely.

However, it would be convenient for me if the video/keyboard modules could be accessed as seamlessly as possible.  Ideally, I would like to be able to use the unmodified LiteX/LiteX-Boards bases, and then plug in custom cores (video/keyboard in my case) without changing LiteX (perhaps out-of-tree cores could be specified with command-line parameters, and then invoked via `importlib.import_module` or similar)?  This feels closely related to https://github.com/enjoy-digital/litex/issues/757 and https://github.com/enjoy-digital/litex/issues/758.

In the short term, I'll update this pull request to remove video/keyboard support; in the long term, I would like to add LiteX/LiteX-Boards hooks so that video and keyboard support remains accessible without actually needing to be packaged within the main repository.

**Comment by garytwong** [comment]
(Resubmitted with only UART/DDR3/Ethernet; video and keyboard removed.)

**Comment by enjoy-digital** [comment]
Thanks for the feedback @garytwong. Even if not all features are integrated in LiteX-Boards, it's possible to create a custom target in your project directly based on the `BaseSoC` from the LiteX-Boards target. You then only need to add your peripherals to this new SoC. For now it's indeed not possible to plug easily new peripheral support in the BIOS without touching LiteX, but while working on enjoy-digital/litex#757 we could try to provide a mechanism for it.

We are already using this in external project like [Linux-on-LiteX-VexRiscv](https://github.com/litex-hub/linux-on-litex-vexriscv) where a custom configuration of the target from LiteX-Boards is used and peripheral added.

I hope this clarify things, if not happy to answer your other questions.

**Comment by garytwong** [comment]
Thank you very much for the attention and comments!  I feel my further questions are starting to drift to another topic, so I will leave this pull request as it is.  Do you think the revised commit (the bare UART/DDR3/Ethernet only revision, in 4e5bb1bf) is suitable to merge?

If so, I will leave other integration ideas for a future issue, because they seem pretty much independent of the basic support.

**Comment by enjoy-digital** [comment]
Thanks for the revised commit, this is fine yes, I'm going to merge it and do minor cosmetic changes to it (just to align it with others platforms/targets).

**Comment by enjoy-digital** [comment]
The few cosmetic changes:
- https://github.com/litex-hub/litex-boards/commit/6c6d8a13934ddca9ab28e851b654929d06bc6d80
- https://github.com/litex-hub/litex-boards/commit/3deeb695318421518fce754cb3a3502cf986ae2d
- https://github.com/litex-hub/litex-boards/commit/19767e1a2aa62ce12f76107c862b0eedb1234ba7
- https://github.com/litex-hub/litex-boards/commit/7525b8772f5b2e17ee4803d27863788ba381d7a1

**Comment by garytwong** [comment]
Fantastic, thank you very much!

**Pull request merged**
